export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'
export const LOGOUT = 'LOGOUT'

export const ADD_USER = 'ADD_USER'
export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'

export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS'
export const ADD_STUDENT = 'ADD_STUDENT'
export const REMOVE_APPLICANT = 'REMOVE_APPLICANT'
export const UPDATE_APPLICANT = 'UPDATE_APPLICANT'

export const GET_ALL_APPLICANTS_SCORE = 'GET_ALL_APPLICANTS_SCORE'
export const GET_APPLICANTS_SCORE = 'GET_APPLICANTS_SCORE'

export const GET_ALL_OFFERING = 'GET_ALL_OFFERING'
export const ENROLL_STUDENT = 'ENROLL_STUDENT'
export const UPDATE_ENROLL_STUDENT = 'UPDATE_ENROLL_STUDENT'
export const GET_STUDENT_ENROLLED = 'GET_STUDENT_ENROLLED'
export const DELETE_STUDENT_ENROLLED = 'DELETE_STUDENT_ENROLLED'

export const ADD_OFFERING = 'ADD_OFFERING'
export const ADD_SCHEDULE = 'ADD_SCHEDULE'
export const GET_ALL_SCHEDULE = 'GET_ALL_SCHEDULE'
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE'
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'

export const GET_GRADES_BY_SCHEDULE = 'GET_GRADES_BY_SCHEDULE'
export const ADD_GRADES_BY_SCHEDULE = 'ADD_GRADES_BY_SCHEDULE'
export const UPDATE_STUDENT_GRADES = 'UPDATE_STUDENT_GRADES'

export const ADD_BILLING = 'ADD_BILLING'
export const GET_ALL_BILLING = 'GET_ALL_BILLING'
export const GET_ALL_STUDENT_BILL = 'GET_ALL_STUDENT_BILL'
export const ADD_PAYMENT = 'ADD_PAYMENT'
export const UPDATE_BILLING = 'UPDATE_BILLING'

export const ADD_CALENDAR = 'ADD_CALENDAR'
export const GET_ALL_CALENDER = 'GET_ALL_CALENDER'
export const UPDATE_CALENDAR = 'UPDATE_CALENDAR'
export const DELETE_CALENDAR = 'DELETE_CALENDAR'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const GET_ALL_NOTIFICATION = 'GET_ALL_NOTIFICATION'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'